### PR TITLE
Added support for only retrieving unread posts and a subset of posts

### PR DESCRIPTION
**Pull request by jmjordan**
Update: Re-submitted pull request with correct commit author.

I am working on a pinboard cli application and needed support to retrieve only unread posts and a subset of posts. I thought this might be a good addition to the library.

### CODE REVIEW

**Comment by mgan59** [comment]
Ideally, I'd like a test to be added.  If you could do that great.  Otherwise I can try to do it later.

Granted I know the tests are sorta lacking, but the plumbing is there to add books marks and maybe do one for `toread` `true` and `false` then ensure the get call matches accordingly.

**Comment by jmjordan** [comment]
Yes, I can add the comments mentioned. Admittedly the if clause is a little nasty, but I didn't want to drastically change how the posts array was populated. You are correct in your assessment of what the 'only_toread' parameter does.

I've never written any unittests, but I can have a go at doing it here.

**Comment by mgan59** [comment]
thats fine, comments would be great.

No better time than now to give it a try.  Few things, these aren't really unit-tests, they are more functional tests as unit-tests typically use mocks/stubs.  Inside of the `tests/test.py` at the top of the file are instructions on how to run the tests, you essentially need to copy the conf file and put your user creds in for pinboard.in.  Note this will actually add bookmarks.  (Why these are actually functional tests and not unittests as unittests wouldn't need your creds nor would it write to the actually api).

Definitely let me know if you have problems or struggle.  I'd rather get this merged then have this sit open.

Thanks again.

**Comment by mgan59** [comment]
Instructions for running tests:

Before running the tests:

``` python
"""
1. Update user credentials at conf.py (see sample_conf.py for example).
2. Consider to backup your data before running this test on real account
or use dedicated sandbox account (the second approach is recommended)."""
```

**Comment by mgan59** [comment]
also, the `.gitignore` is setup to not let you checkin the test/conf.py file you make so no worries about accidental commits.  but you should also double check before commiting :)

**Comment by jmjordan** [comment]
Added unittest for new functionality. Unrelated to my changes I had to change the last assert because it was failing for me if I didn't.

**Comment by mgan59** [comment]
Test looks good.  If you could add just a brief comment as discussed earlier for the logic block about filter/reducing out the `toread` items this will be perfect for merging.

**Comment by jmjordan** [comment]
Added discussed documentation

**Comment by mgan59** [comment]
perfect!  :+1:   Thanks!

**Pull request merged**
